title = "LxLogger Configuration File"

[db]
host = "localhost"
port = 8086
username = "root"
password = "root"

[miniserver]
host = ""
port = 80
username = "admin"
password = ""

[backup]
dest = "/tmp"

#[grafana]
#msmntNameTmpl = "[$r|$c] $n.$s"